[package]
name = "markov-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
serde = { version = "1.0.148", features = ["derive"] }
clap = { version = "4.0.27", features = ["derive"] }
serde_json = { version = "1.0.89" }
